USE [generate]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'APP' AND ROUTINE_NAME = 'GetFiscalYearStartDate') BEGIN
	DROP FUNCTION [App].[GetFiscalYearStartDate]
END

GO

CREATE FUNCTION App.GetFiscalYearStartDate(@SchoolYear SMALLINT)
RETURNS DATE
AS BEGIN
	RETURN CAST(CAST(@SchoolYear - 1 AS VARCHAR) + '-07-01' AS DATE)
END