USE [generate]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'APP' AND ROUTINE_NAME = 'GetRefStateId') BEGIN
	DROP FUNCTION [App].[GetRefStateId]
END

GO


CREATE FUNCTION App.GetRefStateId (@StateAbbreviation CHAR(2))
RETURNS INT
AS BEGIN
	DECLARE @RefStateId INT
	
	SELECT @RefStateId = RefStateId FROM ODS.RefState WHERE Code = @StateAbbreviation

	RETURN @RefStateId
END